### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by runxiyu** [ashutoshkrris/Terminal-Wordle#1]
Software licenses grant people right to use, modify and redistribute your software.  This nice program doesn't seem to have a license.

For simple programs like this, I recommend the MIT Expat License, CC0 or Apache 2.0.  for larger programs, I recommend the GNU GPL.

Under most jurisdictions' copyright law, I can't use this in any way unless otherwise permitted.  

Please add a license, thanks!

**Comment by ashutoshkrris** [comment]
Thanks for the suggestion!
I have added a license
